sudo: false
language: php
php:
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test

before_deploy:
  - ./create-release-archive.sh "$TRAVIS_TAG"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: wp-blog-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    php: 7.0