version: '2'
services:
  app:
    build:
      context: ./
    volumes:
      - ./:/server/http
    working_dir: /server/http
    networks:
      - wpnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/server/http
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - app
    ports:
      - "80:80"
    networks:
      - wpnet

  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
    volumes:
     - ./web/app/uploads/docker-mysqldb:/var/lib/mysql
    networks:
     - wpnet
networks:
  wpnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"