version: '2'
services:
  app:
    build:
      context: ./
    volumes:
      - ./:/server/http
    working_dir: /server/http

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/server/http
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - app
    ports:
      - "80:80"

  redis:
      image: redis:3.2-alpine
      ports:
          - "6379:6379"

  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
    volumes:
     - ./web/app/uploads/docker-mysqldb:/var/lib/mysql
